os: linux

language: php

jobs:
  fast_finish: true
  include:
    - php: 7.3
      dist: bionic
    - php: 7.4
      dist: bionic
    - php: nightly
      dist: bionic
  allow_failures:
    - php: nightly

before_install:
  - travis_retry composer self-update

install: 
  - |
    if [ $TRAVIS_PHP_VERSION = 'nightly' ]; then
      travis_retry composer install --no-interaction --prefer-source --no-suggest --ignore-platform-reqs
    else
      travis_retry composer install --no-interaction --prefer-source --no-suggest
    fi

script: vendor/bin/phpunit
